# Generated by Django 4.0.6 on 2022-07-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_stocks_rename_price_orderblock_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderblock',
            name='order_id',
        ),
    ]
