# Generated by Django 4.0.6 on 2022-07-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_orderblock_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='stock_code',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='orderblock',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.stocks'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_name',
            field=models.CharField(blank=True, choices=[('Jollibee', 'JFC'), ('Ayala Corporation', 'AC'), ('AllDay Mart', 'ALLDY')], max_length=50, null=True),
        ),
    ]
